language: java
jdk:
- openjdk8
before_install:
- export TZ=Asia/Shanghai
install:
- mvn clean package -Dmaven.test.skip=true -Dgpg.skip -Dmaven.javadoc.skip=true -B
  -V
script:
- mvn clean verify -Dgpg.skip -DrepoToken="${COVERALLS_TOKEN}" -Dsonar.projectKey=danshan_asr-assist
  -B -V jacoco:report coveralls:report sonar:sonar
notifications:
  slack: shanhonghao:pdqZbe3SSqGZahgfKsddxPE5
env:
  global:
  - secure: DIj8/Sl9qiHtrsMoZsLsWgcW+5cAwI78S2p090B+bBM+na+d3ach4peLShmXMGYprZEaqPNm61NofkLPkni/KxjMYTEE5UTtUVtgFUWKV82r3EhdfoXKVPRwKiSWvojAb1/bALpgAlIOJKxC4L3/NnxtY8zRAM6TUWwHZ/rRxGhO1ta80WAgfULA2sSQRYy+JvJn2OaTW4+qXpUyKmoJtLbScm+ojnZvHkPRBYCGTNeroU5b/mAWan0uqXKL+wvnp9B4ZmmkF1e6pTVuSaox32hK5jPOkwr3ahAfh0DmDheDKPp+2606y078FKxni5RnmknZxA8QdsFqzkAABSuhX3L+9VN5tphAaxf9sp3cPb/qPH0ONG8S2gGaihUFfppS6jpzq1vzAUyItoN3Twi1jtR7nf0GCs01NlR2kBVMB8lA89KbnShssGmt500jw7gRWElurlr+SEJhi6Wih6rmrn1SXp4xYERkESEQyVrk4pUSYioQfDiKfUWcKoLPwvlzA6qrpvZckZgFiiEGyh9BMvOCQ6Dilz7BB9+RqvoDCenoFrluwd0DT3j6G57lbrimlQIPmVehCSRpJ6EgkjFmNXu4bhXOKfGW2n70cy2rfqAUXgf1MVcNjsuvFPuJWnYaWwmy4DCGM8zDTGWFun6zxgNDuzcwxFWaE4mzckuMREI=

addons:
  sonarcloud:
    organization: "danshan-github"
    token:
      secure: "SXgPLMytpZQ7zNLXrF2u5NG3a+vE1UAojwqDY1M6+TbBOO63H8CpwMcbrAavbAx4jJRE+jLqRgk/1g5iaWaUo2sB1M9XERa+cfuroDD0wuxBb2ybmu3+bkoP3jod87F8KLVZz7IccFQmXT27YB3I/x8/whZ01gEjGDsI9FLz1zdvKTj1uWZiUWRYEip4zVxMG8bOtKNiDo/Srf7/9L2Os21KzG9Ifd7csYdjAwT6+ChYoVSzxYMKxUp6bY0HPCHFDwRQZw5sxK52X3qEyVTEMcjQnzQbswfnJZ7gVfoPtTYSun5tLXx764u3Htzets6jpJH4h9k15QxzTsY5U17qkEv8ZuXVhyk774RpNhly6jEozyHuRgfFEA4e+bLMC5NaIXm3IgKPfm4iGlhu0b57gG3830ZvX3D+tuExCQnQbZJWtR0LctrV6FIneH2OIXmqQvTEjxzr6kxATdbPJlDLmlHQybzJ1EUiVk5MNxqNywZhGqdpxN6bW6EmIdkmKIzUwwF6IlvwN6OjN+R9ifOpxzmN66WGZeR1xhJHVm35pi+jcsJtF18cKhnmKPrsiUPB8hS+VdeEmtmgYsILL4wVSaDRVbdtJrYysiuIq/wrHmOlSbkpotZKIHirN/ZEUDccGxxTrq9/UC5dMD8K9t2bMIDjQuqDQ405kjeiAZWMNaM="
