language: java
jdk:
- openjdk8
before_install:
- export TZ=Asia/Shanghai
install:
- mvn clean package -Dmaven.test.skip=true -Dgpg.skip -Dmaven.javadoc.skip=true -B
  -V
script:
- mvn clean verify -Dgpg.skip -DrepoToken="${COVERALLS_TOKEN}" -Dsonar.login="${SONARCLOUD_TOKEN}"
  -B -V jacoco:report coveralls:report sonar:sonar
notifications:
  slack: shanhonghao:pdqZbe3SSqGZahgfKsddxPE5
env:
  global:
  - secure: DIj8/Sl9qiHtrsMoZsLsWgcW+5cAwI78S2p090B+bBM+na+d3ach4peLShmXMGYprZEaqPNm61NofkLPkni/KxjMYTEE5UTtUVtgFUWKV82r3EhdfoXKVPRwKiSWvojAb1/bALpgAlIOJKxC4L3/NnxtY8zRAM6TUWwHZ/rRxGhO1ta80WAgfULA2sSQRYy+JvJn2OaTW4+qXpUyKmoJtLbScm+ojnZvHkPRBYCGTNeroU5b/mAWan0uqXKL+wvnp9B4ZmmkF1e6pTVuSaox32hK5jPOkwr3ahAfh0DmDheDKPp+2606y078FKxni5RnmknZxA8QdsFqzkAABSuhX3L+9VN5tphAaxf9sp3cPb/qPH0ONG8S2gGaihUFfppS6jpzq1vzAUyItoN3Twi1jtR7nf0GCs01NlR2kBVMB8lA89KbnShssGmt500jw7gRWElurlr+SEJhi6Wih6rmrn1SXp4xYERkESEQyVrk4pUSYioQfDiKfUWcKoLPwvlzA6qrpvZckZgFiiEGyh9BMvOCQ6Dilz7BB9+RqvoDCenoFrluwd0DT3j6G57lbrimlQIPmVehCSRpJ6EgkjFmNXu4bhXOKfGW2n70cy2rfqAUXgf1MVcNjsuvFPuJWnYaWwmy4DCGM8zDTGWFun6zxgNDuzcwxFWaE4mzckuMREI=
  - secure: hrQiBTdq60a/sgozYdUZN3iQ3U3S3w6QNaLYLlhNdi2fbSsDuIIT/ZYiBc/T3AsyHVR1L4QA6rf98AU6LTQpaNQfay+9xo2jZF6aBjXEST8r6KwFrrXwja/u1i2JSwEFL1m2CVWYOr9UfHJhgTEqjsJj7zuxkDsPDDcmMv6B1V3jhY69F390px7z9xYuFx/fwlKRDTgrat2mb5Iw6LDLxSWp6M2zuTILEU7X4x5jUONoooDj5X1RLZj1qzRs3xUsLZd7y6izHtfWcHSkLVkV8/JmOHVhMGiDJTzXMrsuoFEFmU0gAkzVinbKwqur1fKdx35Uv8MdiFuzzXHIlNkLVR5fYP5E3Blm8tSL4BW7YnvLvQ9dNursWrVFJNh0JOyow3v1B0pT6Pvwa1n2YSaGOnG8RQjwjO26QDfmII1+0v5lCHnDQFtOL7bDYUYRgWMfTk9IrCIDcIzdslg1cLpQQZewYaADNzR97PitxPkseTKzjonnIzDQ1tCXvgXHeG+D9LumaffeLn0fsCRqGpupqsJW7YDuInqrdxOOMfYmBKM+eEAIUU7+sxhnQvVHRFMOqMFDPi0JcQ6YmZPj87yG3fGiterTn6EeDIufDb1+4vgRBxYB4s4qvtBHn2/irGd7K4F9Tz++TDwqFm+WxUbn7meKbGxA4Mm6DbZWknJPKg0=
