language: java
jdk:
  - openjdk8
before_install:
  - export TZ=Asia/Shanghai
install:
  - mvn clean package -Dmaven.test.skip=true -Dgpg.skip -B -V
after_success:
  - mvn clean verify -Dgpg.skip -DrepoToken="${COVERALLS_TOKEN}" -Dsonar.login="${SONARCLOUD_TOKEN} -B -V jacoco:report coveralls:report sonar:sonar"
notifications:
  slack: shanhonghao:pdqZbe3SSqGZahgfKsddxPE5
env:
  global:
    - secure: DIj8/Sl9qiHtrsMoZsLsWgcW+5cAwI78S2p090B+bBM+na+d3ach4peLShmXMGYprZEaqPNm61NofkLPkni/KxjMYTEE5UTtUVtgFUWKV82r3EhdfoXKVPRwKiSWvojAb1/bALpgAlIOJKxC4L3/NnxtY8zRAM6TUWwHZ/rRxGhO1ta80WAgfULA2sSQRYy+JvJn2OaTW4+qXpUyKmoJtLbScm+ojnZvHkPRBYCGTNeroU5b/mAWan0uqXKL+wvnp9B4ZmmkF1e6pTVuSaox32hK5jPOkwr3ahAfh0DmDheDKPp+2606y078FKxni5RnmknZxA8QdsFqzkAABSuhX3L+9VN5tphAaxf9sp3cPb/qPH0ONG8S2gGaihUFfppS6jpzq1vzAUyItoN3Twi1jtR7nf0GCs01NlR2kBVMB8lA89KbnShssGmt500jw7gRWElurlr+SEJhi6Wih6rmrn1SXp4xYERkESEQyVrk4pUSYioQfDiKfUWcKoLPwvlzA6qrpvZckZgFiiEGyh9BMvOCQ6Dilz7BB9+RqvoDCenoFrluwd0DT3j6G57lbrimlQIPmVehCSRpJ6EgkjFmNXu4bhXOKfGW2n70cy2rfqAUXgf1MVcNjsuvFPuJWnYaWwmy4DCGM8zDTGWFun6zxgNDuzcwxFWaE4mzckuMREI=
    - secure: PO73eILs19JBsLi0nFFDSg0b9r1pLFOMxPINxip4kpRtPnh7OG7Tiv/CHaDyhuBGmRSV4R4kz2IYkotHNmTy87dawQXMiqUvZ6TqCj4lCsElrUc124k6bvdw28Rokh402tBV9mCyFl4ycoEgxwTj5UnLIaTszXvR3Jc3SOZWtXbdyWtBZrxSkoue5GokAgizskJUV/fIMoJ9whTffnLZsJE0T4/eYHpKqMGr6Rtm9rhEAO+8j07pd6hNcRk8ZF/tzyp95YE3mdalMIJZo23keg9DB1Jh4Cr8SpLrM/EUvrYJxtAaihUprjmh01GcaTl7bjKLkXHdbtSvPleq0dHmLWuvG0+xelbmQO3yld+AkMjdZqadvVeTdBVvXZuKpYEUkxmLgkRWMHckUuOYGGI3n1ZuRrlRWc3j3zw4JjA4fniQ0mUtL3qzDvL2W99cnjzd6P2EAIIGxTsrbmf60mI8OmrZpVdnCujBnM/x8T+d/iSqC/EsQZJanvPG6M9GOh9c+ekKmZMUoqkMMYQj+rGTJ2Q619t+J7MkJ1pSQCmIVHGtYNOeluj+rGBG2pOx9LizKOQSW+IW3dmDjfzbeEZrqCwvOhRg462dzeItiAktE1+Ya5b9feEulvhwNPQlH2mDhAaShpH65YrEB5t9tqKNc/eakdbMJYT9oVk6L6ZmLCg=
