language: java
jdk:
- openjdk8
before_install:
- export TZ=Asia/Shanghai
install:
- mvn clean package -Dmaven.test.skip=true -Dgpg.skip -Dmaven.javadoc.skip=true -B
  -V
script:
- mvn clean verify -Dgpg.skip -DrepoToken="${COVERALLS_TOKEN}" -Dsonar.login="${SONARCLOUD_TOKEN}"
  -B -V jacoco:report coveralls:report sonar:sonar
notifications:
  slack: shanhonghao:pdqZbe3SSqGZahgfKsddxPE5
env:
  global:
  - secure: DIj8/Sl9qiHtrsMoZsLsWgcW+5cAwI78S2p090B+bBM+na+d3ach4peLShmXMGYprZEaqPNm61NofkLPkni/KxjMYTEE5UTtUVtgFUWKV82r3EhdfoXKVPRwKiSWvojAb1/bALpgAlIOJKxC4L3/NnxtY8zRAM6TUWwHZ/rRxGhO1ta80WAgfULA2sSQRYy+JvJn2OaTW4+qXpUyKmoJtLbScm+ojnZvHkPRBYCGTNeroU5b/mAWan0uqXKL+wvnp9B4ZmmkF1e6pTVuSaox32hK5jPOkwr3ahAfh0DmDheDKPp+2606y078FKxni5RnmknZxA8QdsFqzkAABSuhX3L+9VN5tphAaxf9sp3cPb/qPH0ONG8S2gGaihUFfppS6jpzq1vzAUyItoN3Twi1jtR7nf0GCs01NlR2kBVMB8lA89KbnShssGmt500jw7gRWElurlr+SEJhi6Wih6rmrn1SXp4xYERkESEQyVrk4pUSYioQfDiKfUWcKoLPwvlzA6qrpvZckZgFiiEGyh9BMvOCQ6Dilz7BB9+RqvoDCenoFrluwd0DT3j6G57lbrimlQIPmVehCSRpJ6EgkjFmNXu4bhXOKfGW2n70cy2rfqAUXgf1MVcNjsuvFPuJWnYaWwmy4DCGM8zDTGWFun6zxgNDuzcwxFWaE4mzckuMREI=
  - secure: uQp5zoTeakD0UI6Y2qfkeaXMSZzEHLgVi2QSBouklRrc1VGQOtU75+oWz5vGIRpYNCkl/pW9fK7TDhNAS5o6KLLcB+Y9sLbIvg97btX2OZyB5iLlCSVz5V9Z8+uvrgzNCy/Y1o2rvGmEmRp6KBcfo0TXJdJR8v+ZrHoQHfL2PHorfAZdpFEZ2lYUt5kFO+dOr8LIrie5WBLVeC0VOiQPkzIwim16flZihfWMtLje6vWrY+Iif8zmChC0GmFfj8K9XTFEOnTXbQeIBPQngxnGvsOp5wo67N0CViiz03GyCIX2AIFAhSrL6hNtsJUvrl10ac3dny9xA9xYtTkaoFqeTFeaGbZFvOsVQOW0yrR7E51L3BLYg+4Z3ev43CzNoVMwfKoHd+gTR6KH1xlvE97d3WDD1Den8eFPEtHXinqZXBPh6fub8WOCi7DgVVy6n5ELSOb0J+pqHtv9p/Q3D4m8hMJiob9gsVL2XOdHy+4JeIbRuhzmUSJJOlPq0pfEXS0PBjvGVORdgdT31VtYZobRwZVLd86Tsgk8bwelw/nPkyf5HhEkPf7sEx+RTQRRF/WYwvSHazRwp8YdEfH/WHzZEG8sY5eGwio/9Oc0Ny205a77PObvHViVCj5W/dOlqOdY2v2h/6DhQ9+56ICNY3PhM19sqMj8zRveXC72i06FYD0=
