name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B -V clean package -Dgpg.skip
#    - name: Test with Maven
#      run: mvn -B -V clean jacoco:report coveralls:report -DrepoToken=$repoToken
#      env:
#        repoToken: ${{ secrets.COVERALLS_ASR_ASSIST_TOKEN }}
#    - name: Coveralls GitHub Action
#      uses: coverallsapp/github-action@v1.0.1
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
